/**
 * Regenerate src/client/art.generated.ts from the baked skin artwork in
 * assets/. Every final is a small webp (the favicon and paper texture stay
 * png) embedded as a base64 data URI so the packed skin never reads a file
 * or URL at runtime.
 *
 * Baked assets come from scripts/bake-art.py — run it first:
 *   python scripts/bake-art.py
 *   node scripts/generate-art.mjs
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')

const THEME_ART = {
  ...Object.fromEntries([
    'ribbon-left', 'ribbon-right', 'ribbon-tile',
    'new-left', 'new-right', 'new-tile',
    'settings-left', 'settings-right', 'settings-tile',
    'corner-tl', 'corner-tr', 'corner-bl', 'corner-br', 'garland',
  ].map(name => [`sidebar_${name.replaceAll('-', '_')}`, {
    source: resolve(projectRoot, `assets/lpp-sidebar-${name}.webp`), type: 'image/webp',
  }])),
  backgroundDay: {
    source: resolve(projectRoot, 'assets/lpp-bg-day.webp'),
    type: 'image/webp',
  },
  backgroundNight: {
    source: resolve(projectRoot, 'assets/lpp-bg-night.webp'),
    type: 'image/webp',
  },
  charLeft: {
    source: resolve(projectRoot, 'assets/lpp-char-left.webp'),
    type: 'image/webp',
  },
  charRight: {
    source: resolve(projectRoot, 'assets/lpp-char-right.webp'),
    type: 'image/webp',
  },
  workspaceOsmanthus: {
    source: resolve(projectRoot, 'assets/lpp-workspace-osmanthus.webp'),
    type: 'image/webp',
  },
  chibi: {
    source: resolve(projectRoot, 'assets/lpp-chibi.webp'),
    type: 'image/webp',
  },
  composerEmblem: {
    source: resolve(projectRoot, 'assets/lpp-composer-emblem.webp'),
    type: 'image/webp',
  },
  ...Object.fromEntries([
    ['composerCornerTl', 'corner-tl'], ['composerCornerTr', 'corner-tr'],
    ['composerCornerBl', 'corner-bl'], ['composerCornerBr', 'corner-br'],
    ['composerTopStart', 'top-start'], ['composerTopEnd', 'top-end'],
    ['composerBottomStart', 'bottom-start'], ['composerBottomEnd', 'bottom-end'],
    ['composerLeftStart', 'left-start'], ['composerLeftEnd', 'left-end'],
    ['composerRightStart', 'right-start'], ['composerRightEnd', 'right-end'],
  ].map(([key, part]) => [key, {
    source: resolve(projectRoot, `assets/lpp-composer-${part}.webp`),
    type: 'image/webp',
  }])),
  cornerTl: {
    source: resolve(projectRoot, 'assets/lpp-corner-tl.webp'),
    type: 'image/webp',
  },
  cornerTr: {
    source: resolve(projectRoot, 'assets/lpp-corner-tr.webp'),
    type: 'image/webp',
  },
  cornerBl: {
    source: resolve(projectRoot, 'assets/lpp-corner-bl.webp'),
    type: 'image/webp',
  },
  cornerBr: {
    source: resolve(projectRoot, 'assets/lpp-corner-br.webp'),
    type: 'image/webp',
  },
  crest: {
    source: resolve(projectRoot, 'assets/lpp-crest.webp'),
    type: 'image/webp',
  },
  plaque: {
    source: resolve(projectRoot, 'assets/lpp-plaque.webp'),
    type: 'image/webp',
  },
  waistToken: {
    source: resolve(projectRoot, 'assets/lpp-token.webp'),
    type: 'image/webp',
  },
  brocade: {
    source: resolve(projectRoot, 'assets/lpp-brocade.webp'),
    type: 'image/webp',
  },
  trimTop: {
    source: resolve(projectRoot, 'assets/lpp-trim-top.webp'),
    type: 'image/webp',
  },
  trimBottom: {
    source: resolve(projectRoot, 'assets/lpp-trim-bottom.webp'),
    type: 'image/webp',
  },
  favicon: {
    source: resolve(projectRoot, 'assets/lpp-favicon.png'),
    type: 'image/png',
  },
  paperTexture: {
    source: resolve(projectRoot, 'assets/lpp-paper-texture.png'),
    type: 'image/png',
  },
}

function toDataUri(buffer, type) {
  return `data:${type};base64,${buffer.toString('base64')}`
}

let output = `/**
 * Generated by scripts/generate-art.mjs — do not edit by hand.
 *
 * All artwork is embedded as base64 data URIs so the packed skin is fully
 * self-contained. Artwork source:
 * - 《哀鸿：城破十日记》同人角色「林翩翩」立绘
 * - B 站作者：露痴了么
 * - Project and third-party terms: see LICENSE, LICENSE-ASSETS.md, and NOTICE.
 */

`

output += 'export const LINPIANPIAN_ART = {\n'
for (const [name, asset] of Object.entries(THEME_ART)) {
  const source = await readFile(asset.source)
  output += `  ${JSON.stringify(name)}: [\n`
  const dataUri = toDataUri(source, asset.type)
  for (let index = 0; index < dataUri.length; index += 20000) {
    output += `    ${JSON.stringify(dataUri.slice(index, index + 20000))},\n`
  }
  output += '  ].join(\'\'),\n'
}
output += '} as const\n'

const target = resolve(projectRoot, 'src/client/art.generated.ts')
await mkdir(dirname(target), { recursive: true })
await writeFile(target, output)
console.log(`[generate-art] wrote ${target} (${output.length} chars)`)
